import os
import json
import mimetypes
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload
from google.oauth2 import service_account
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request
from dotenv import load_dotenv

# --------------------------------------------------
# 🌍 Load environment variables
# --------------------------------------------------
load_dotenv()
SCOPES = ["https://www.googleapis.com/auth/drive.file"]

# --------------------------------------------------
# 🧩 Load credentials (OAuth > Service Account)
# --------------------------------------------------
def get_drive_service():
    creds = None
    credentials_path = os.getenv("GOOGLE_CREDENTIALS_PATH", "").strip()

    if not credentials_path or not os.path.exists(credentials_path):
        raise FileNotFoundError("❌ No credentials file found at GOOGLE_CREDENTIALS_PATH in .env")

    # -------------------------------
    # 1️⃣ Try OAuth (client_secret.json)
    # -------------------------------
    if "client_secret" in credentials_path:
        print("🔐 Using OAuth (user login)...")
        token_path = "credentials/token.json"

        # Try loading existing OAuth token
        if os.path.exists(token_path):
            from google.oauth2.credentials import Credentials
            creds = Credentials.from_authorized_user_file(token_path, SCOPES)

        # If no token or expired, trigger new login flow
        if not creds or not creds.valid:
            if creds and creds.expired and creds.refresh_token:
                creds.refresh(Request())
            else:
                flow = InstalledAppFlow.from_client_secrets_file(credentials_path, SCOPES)
                creds = flow.run_local_server(port=0)
            with open(token_path, "w") as token:
                token.write(creds.to_json())
                print("✅ Saved OAuth token for future uploads.")

        return build("drive", "v3", credentials=creds)

    # -------------------------------
    # 2️⃣ Fallback: Service Account
    # -------------------------------
    else:
        print("🧠 Using Service Account credentials...")
        creds = service_account.Credentials.from_service_account_file(credentials_path, scopes=SCOPES)
        return build("drive", "v3", credentials=creds)


# --------------------------------------------------
# ☁️ Upload File Function
# --------------------------------------------------
def upload_to_drive(file_path, folder_id=None):
    """Uploads a file to Google Drive (inside specified folder if provided)."""
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"⚠️ File not found: {file_path}")

    service = get_drive_service()
    file_name = os.path.basename(file_path)
    mime_type, _ = mimetypes.guess_type(file_path)

    file_metadata = {"name": file_name}
    if folder_id:
        file_metadata["parents"] = [folder_id]

    media = MediaFileUpload(file_path, mimetype=mime_type, resumable=True)
    print(f"☁️ Uploading {file_name} to Google Drive...")

    uploaded = service.files().create(
        body=file_metadata,
        media_body=media,
        fields="id, webViewLink"
    ).execute()

    file_id = uploaded.get("id")
    web_link = uploaded.get("webViewLink")

    print(f"✅ Uploaded successfully → {web_link}")
    return file_id


# --------------------------------------------------
# 🧪 Test upload
# --------------------------------------------------
if __name__ == "__main__":
    print("☁️ Uploading test_upload.pdf to Google Drive...")
    test_file = "test_upload.pdf"

    # create test file if missing
    if not os.path.exists(test_file):
        with open(test_file, "w") as f:
            f.write("This is a test file generated by BookForge AI.")

    try:
        folder_id = os.getenv("GOOGLE_DRIVE_FOLDER_ID")
        upload_to_drive(test_file, folder_id)
    except Exception as e:
        print(f"❌ Test upload failed: {e}")
