import os
import json
from datetime import datetime
from fpdf import FPDF

# Font file paths (make sure these exist)
FONT_DIR = os.path.join("assets")
FONT_REG = os.path.join(FONT_DIR, "DejaVuSans.ttf")
FONT_BOLD = os.path.join(FONT_DIR, "DejaVuSans-Bold.ttf")
FONT_ITALIC = os.path.join(FONT_DIR, "DejaVuSans-Oblique.ttf")

class PDF(FPDF):
    def header(self):
        if self.page_no() != 1:
            self.set_font("DejaVu", "B", 12)
            self.cell(0, 10, self.title, align="C", ln=True)
            self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("DejaVu", "I", 10)
        self.cell(0, 10, f"Page {self.page_no()}", align="C")

def generate_pdf_from_ebook(ebook_path):
    print(f"📖 Loading eBook JSON from: {ebook_path}")
    with open(ebook_path, "r", encoding="utf-8") as f:
        ebook = json.load(f)

    title = ebook.get("title", "Untitled eBook")
    subtitle = ebook.get("subtitle", "")
    toc = ebook.get("table_of_contents", [])
    chapters = ebook.get("chapters", [])
    summary = ebook.get("executive_summary", "")
    created_at = ebook.get("created_at", datetime.now().strftime("%Y-%m-%d"))

    os.makedirs("data/pdfs", exist_ok=True)
    safe_title = title.replace(" ", "_").replace("'", "").lower()
    output_path = f"data/pdfs/{safe_title}_{datetime.now().strftime('%Y%m%d_%H%M')}.pdf"

    pdf = PDF()
    pdf.set_auto_page_break(auto=True, margin=15)

    # ✅ Add all font variants
    pdf.add_font("DejaVu", "", FONT_REG, uni=True)
    pdf.add_font("DejaVu", "B", FONT_BOLD, uni=True)
    pdf.add_font("DejaVu", "I", FONT_ITALIC, uni=True)

    pdf.title = title
    pdf.add_page()

    # 🧱 COVER PAGE
    pdf.set_font("DejaVu", "B", 28)
    pdf.cell(0, 20, title, ln=True, align="C")
    pdf.set_font("DejaVu", "", 16)
    pdf.cell(0, 12, subtitle, ln=True, align="C")
    pdf.ln(20)
    pdf.set_font("DejaVu", "", 12)
    pdf.multi_cell(0, 8, summary)
    pdf.add_page()

    # 📑 TABLE OF CONTENTS
    if toc:
        pdf.set_font("DejaVu", "B", 20)
        pdf.cell(0, 15, "Table of Contents", ln=True)
        pdf.set_font("DejaVu", "", 12)
        for item in toc:
            pdf.cell(0, 8, item, ln=True)
        pdf.add_page()

    # 🧩 CHAPTERS
    for idx, ch in enumerate(chapters, start=1):
        chapter_title = ch.get("chapter_title", f"Chapter {idx}")
        content = ch.get("content", "")
        takeaway = ch.get("takeaway")

        pdf.set_font("DejaVu", "B", 16)
        pdf.multi_cell(0, 10, chapter_title)
        pdf.ln(3)

        pdf.set_font("DejaVu", "", 12)
        pdf.multi_cell(0, 8, content)
        pdf.ln(4)

        if takeaway:
            pdf.set_fill_color(240, 240, 240)
            pdf.set_font("DejaVu", "I", 12)
            pdf.multi_cell(0, 8, f"Takeaway: {takeaway}", fill=True)
            pdf.ln(8)

    # 🦶 FOOTER INFO
    pdf.add_page()
    pdf.set_font("DejaVu", "I", 10)
    pdf.multi_cell(0, 6, f"Generated by BookForge AI • {created_at}")

    pdf.output(output_path)
    print(f"✅ Professional PDF saved → {output_path}")
    return output_path


if __name__ == "__main__":
    data_dir = "data/ebooks"
    latest = max(
        [os.path.join(data_dir, f) for f in os.listdir(data_dir) if f.endswith(".json")],
        key=os.path.getmtime
    )
    print(f"📘 Auto-detected eBook: {latest}")
    generate_pdf_from_ebook(latest)
